SSH password: 
[KeyJ1dWlkIjogIjhmMjdmYzMyLTg4NTctNGU3NS04YzdhLTA5YWZjOWUzYzVkYyJ9[64D[K[Ke30=[4D[K[KeyJ1dWlkIjogIjAwNTA1NmJiLTRlMDctMjBmYy05NjA3LTAwMDAwMDAwMDAwMiJ9[64D[K
PLAY [localhost] ***************************************************************
[Ke30=[4D[K[KeyJ1dWlkIjogIjAwNTA1NmJiLTRlMDctMjBmYy05NjA3LTAwMDAwMDAwMDAwZCJ9[64D[K
TASK [Gathering Facts] *********************************************************
[Ke30=[4D[K[KeyJ1dWlkIjogImI0Y2IyMGM4LWNhMzctNDIyMi1hZWRmLTUzMTNhOGE1YzA1OCJ9[64D[K[0;32mok: [127.0.0.1][0m
[Ke30=[4D[K[KeyJ1dWlkIjogIjAwNTA1NmJiLTRlMDctMjBmYy05NjA3LTAwMDAwMDAwMDAwNCJ9[64D[K
TASK [command] *****************************************************************
[Ke30=[4D[K[KeyJ1dWlkIjogIjNkZGRlYjVmLWUwMzctNGIwZi1iOThhLWRiYTRiMWY2ZTA4NyJ9[64D[K[0;31mfatal: [127.0.0.1 -> 127.0.0.1]: FAILED! => {"changed": true, "cmd": "python ise_create_user_v1.py 'Lalshwa' 'Lal' 'K' 'Wipro@123' 'lal.k@abc.com' 'Student'", "delta": "0:02:07.429766", "end": "2018-02-16 14:21:53.978221", "failed": true, "rc": 1, "start": "2018-02-16 14:19:46.548455", "stderr": "Traceback (most recent call last):\n  File \"ise_create_user_v1.py\", line 60, in <module>\n    conn.request(\"POST\", \"/ers/config/internaluser/\", headers=headers, body=req_body_json)\n  File \"/usr/lib64/python2.7/httplib.py\", line 1017, in request\n    self._send_request(method, url, body, headers)\n  File \"/usr/lib64/python2.7/httplib.py\", line 1051, in _send_request\n    self.endheaders(body)\n  File \"/usr/lib64/python2.7/httplib.py\", line 1013, in endheaders\n    self._send_output(message_body)\n  File \"/usr/lib64/python2.7/httplib.py\", line 864, in _send_output\n    self.send(msg)\n  File \"/usr/lib64/python2.7/httplib.py\", line 826, in send\n    self.connect()\n  File \"/usr/lib64/python2.7/httplib.py\", line 1227, in connect\n    HTTPConnection.connect(self)\n  File \"/usr/lib64/python2.7/httplib.py\", line 807, in connect\n    self.timeout, self.source_address)\n  File \"/usr/lib64/python2.7/socket.py\", line 571, in create_connection\n    raise err\nsocket.error: [Errno 110] Connection timed out", "stderr_lines": ["Traceback (most recent call last):", "  File \"ise_create_user_v1.py\", line 60, in <module>", "    conn.request(\"POST\", \"/ers/config/internaluser/\", headers=headers, body=req_body_json)", "  File \"/usr/lib64/python2.7/httplib.py\", line 1017, in request", "    self._send_request(method, url, body, headers)", "  File \"/usr/lib64/python2.7/httplib.py\", line 1051, in _send_request", "    self.endheaders(body)", "  File \"/usr/lib64/python2.7/httplib.py\", line 1013, in endheaders", "    self._send_output(message_body)", "  File \"/usr/lib64/python2.7/httplib.py\", line 864, in _send_output", "    self.send(msg)", "  File \"/usr/lib64/python2.7/httplib.py\", line 826, in send", "    self.connect()", "  File \"/usr/lib64/python2.7/httplib.py\", line 1227, in connect", "    HTTPConnection.connect(self)", "  File \"/usr/lib64/python2.7/httplib.py\", line 807, in connect", "    self.timeout, self.source_address)", "  File \"/usr/lib64/python2.7/socket.py\", line 571, in create_connection", "    raise err", "socket.error: [Errno 110] Connection timed out"], "stdout": "", "stdout_lines": []}[0m
[Ke30=[4D[K[KeyJ1dWlkIjogIjQzYmVhZWUzLWU5MWMtNGU2NC1hZmE3LWEwNmFjZmQzYjBhYyJ9[64D[K
PLAY RECAP *********************************************************************
[0;31m127.0.0.1[0m                  : [0;32mok=1   [0m changed=0    unreachable=0    [0;31mfailed=1   [0m

[Ke30=[4D[K